docs(readme): adapt for v2 release
snek-at/jaen pull request #33
Opened 2021-09-02 16:27 UTC by kleberbaum

- Get Up and Running in 5 Minutes
- Motivation
- How to Code
- Trivia
- Creators

Adapt the readme for the upcoming V2.0.0 release.

2021-09-03 10:49 UTC, petute approved these changes
Should be ready for merge.

2021-09-03 22:18 UTC, petschna reviewed
Should be ok to merge.

Really awesome what you accomplished.
smooch <3

2021-09-03 22:22 UTC, petschna approved these changes
Should be ok to merge.

2021-09-04 09:50 UTC, Aichnerc approved these changes
Does the Pull Request description follow any template?

Content is looking good and should therefore be able to merged.

2021-09-05 21:30 UTC, evilpro approved these changes

2021-09-06 10:25 UTC, simonprast approved these changes
Thank you for implementing the improvements. Should be ready to merge now.

2021-09-26 23:01 UTC, schettn requested changes
have a look

2021-09-26 23:01 UTC, schettn commented on README.md
> +The inofficial mascot of this project is a girl holding an electric guitar.
Rlly? 👀

2021-09-26 23:01 UTC, closed without merging